name: .NET Core Build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: "windows-latest"
            rid: "win-x64"
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core 8.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: "8.0.300"
    - name: archiving dotnet tool
      run: "powershell ./build.ps1 --target Archive BuildInstaller --configuration Release --runtime \"${{matrix.rid}}\""
    - name: upload archive
      uses: actions/upload-artifact@v1
      with:
        name: "WEventViewer-win-x64"
        path: "dist/publish/Release/${{matrix.rid}}/WEventViewer-${{matrix.rid}}.zip"
    - name: upload installer
      uses: actions/upload-artifact@v1
      with:
        name: "WEventViewer-win-x64"
        path: "dist/installer/Release/en-US/WEventViewer.Installer.msi"
