on:
  release:
    types:
      - published
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: "windows-latest"
            rid: "win-x64"
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core 8.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: "8.0.300"
    - name: archiving dotnet tool
      run: "powershell ./build.ps1 --target Archive --configuration Release --runtime \"${{matrix.rid}}\""
    - name: upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: "WEventViewer-win-x64"
        path: "dist/publish/Release/${{matrix.rid}}/WEventViewer-${{matrix.rid}}.zip"
  release:
    needs: build
    runs-on: "windows-latest"
    steps:
      - name: download WEventViewer.zip
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      - name: upload zip to gh release
        run: gh release upload ${{github.event.release.tag_name}} artifacts/WEventViewer-win-x64/WEventViewer-win-x64.zip
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}